[package]
authors = ["Alex Pearson <alex@alexpear.com>"]
edition = "2018"
name = "resumaester"
version = "0.1.0"

[dependencies]
getopts = "*"
serde_json = "1.0"

[dependencies.serde]
features = ["derive"]
version = "1.0"
